# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='formatted_test',
            new_name='formatted_text',
        ),
    ]
